name:         Nuko
version:      0.1.0.0
github:       "felipegchi/Nuko"
license:      BSD3
author:       "Felipe G"
maintainer:   "chiyokuoni@gmail.com"
copyright:    "2022 Felipe G"

description: <https://github.com/githubuser/Nuko#readme>

dependencies:
  - base >= 4.7 && < 5
  - pretty-simple

default-extensions:
  - DuplicateRecordFields
  - OverloadedRecordDot
  - OverloadedStrings
  - StandaloneDeriving
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - FlexibleInstances
  - RankNTypes
  - LambdaCase
  - TypeFamilies
  - GADTs
  - ConstraintKinds
  - FlexibleContexts
  - FunctionalDependencies
  - UndecidableInstances
  
ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missing-deriving-strategies
  - -Wno-missing-kind-signatures
  - -Wno-prepositive-qualified-module
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-safe
  - -Wno-missing-exported-signatures
  - -Wno-unsafe
  - -Wno-missed-specialisations

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
  - bytestring
  - text
  - mtl
  - array
  - transformers
  - pretty-terminal
  - containers
  - unordered-containers

executables:
  Nuko-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko

tests:
  Nuko-test:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko
      - filepath
      - tasty
      - tasty-golden
      - tasty-hunit
      - bytestring
      - text
