name: Nuko
version: 0.1.0.0
github: "felipegchi/Nuko"
license: BSD3
author: "Felipe G"
maintainer: "chiyokuoni@gmail.com"
copyright: "2022 Felipe G"

description: <https://github.com/githubuser/Nuko#readme>

dependencies:
  - base >= 4.16.0.0
  - relude ^>= 1.1.0.0
  - aeson

default-extensions:
  - DuplicateRecordFields
  - OverloadedRecordDot
  - OverloadedStrings
  - StandaloneDeriving
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - FlexibleInstances
  - LambdaCase
  - TypeFamilies
  - NoImplicitPrelude
  - FlexibleContexts
  - OverloadedStrings
  - DataKinds
  - UndecidableInstances
  - FunctionalDependencies
  - ConstraintKinds
  - TemplateHaskell
  - RankNTypes
  - DeriveGeneric
  - TupleSections
  - TypeOperators
  - AllowAmbiguousTypes
  - DefaultSignatures
  - UndecidableInstances
  - GADTs
  - ImpredicativeTypes
  - StrictData
  - DeriveFunctor
  - PatternSynonyms
  - ScopedTypeVariables
  - ImportQualifiedPost

ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missing-deriving-strategies
  - -Wno-missing-kind-signatures
  - -Wno-prepositive-qualified-module
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-safe
  - -Wno-missing-exported-signatures
  - -Wno-unsafe
  - -Wno-missed-specialisations

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - mtl
    - bytestring
    - array
    - monad-chronicle
    - these
    - microlens-platform
    - containers
    - unordered-containers
    - hashable
    - text
    - pretty-terminal

executables:
  Nuko-Cli-exe:
    main: Main.hs
    source-dirs: cli
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko
      - bytestring
      - these

tests:
  Nuko-test:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko
      - filepath
      - tasty
      - tasty-golden
      - bytestring
      - text
      - these
      - pretty-simple
      - monad-chronicle
      - mtl
    default-extensions:
      - NoImplicitPrelude
      - OverloadedStrings
