name: Nuko
version: 0.1.0.0
github: "felipegchi/Nuko"
license: BSD3
author: "Felipe G"
maintainer: "chiyokuoni@gmail.com"
copyright: "2022 Felipe G"

description: <https://github.com/githubuser/Nuko#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - text
  - bytestring
  - containers
  - array

default-extensions:
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - TypeFamilies
  - FlexibleInstances
  - LambdaCase
  - StandaloneDeriving
  - FlexibleContexts
  - DataKinds
  - GADTs
  - PatternSynonyms
  - ConstraintKinds 

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - pretty-terminal

ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missing-deriving-strategies
  - -Wno-prepositive-qualified-module
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-safe
  - -Wno-unsafe

executables:
  Nuko-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko

tests:
  Nuko-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko
      - filepath
      - tasty
      - tasty-golden
      - tasty-hunit
