name: Nuko
version: 0.1.0.0
github: "felipegchi/Nuko"
license: BSD3
author: "Felipe G"
maintainer: "chiyokuoni@gmail.com"
copyright: "2022 Felipe G"

description: <https://github.com/githubuser/Nuko#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - text
  - bytestring
  - containers
  - array

default-extensions:
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - TypeFamilies
  - FlexibleInstances
  - LambdaCase
  - StandaloneDeriving

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - pretty-terminal

executables:
  Nuko-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko

tests:
  Nuko-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Nuko
      - tasty-golden
      - tasty
      - filepath
